{
  "hash": "d421fa3a1ccf31cebfa2ecd1c26c25b3",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Choosing the Cell Resolution\"\njupyter: python3\n---\n\n```{=html}\n<style>\ntable.dataframe { width: auto; max-width: 90%; font-size: 0.85em; margin-left: auto; margin-right: auto; }\n</style>\n```\n\n\n# The resolution problem\n\nThe scale-decomposition bound on preferential-sampling bias (Prop.\n*scale-decomposition* of the methodology) reads, on an equal-measure partition\n$\\mathcal{P}_K$ with $K=K_{\\mathrm{lon}}K_{\\mathrm{lat}}K_t$,\n$$\n  \\big|B_{\\mathrm{samp}}\\big|\n  \\;\\le\\;\\sigma_{w^{\\star}}\\,\\sigma_{Y^{\\star}}\n        \\;+\\;\\sigma_{w^{\\perp}}\\,\\sigma_{Y^{\\perp}} ,\n$$\nwith field factors $\\sigma_{Y^\\star}=\\|y^\\star\\|_{L^2(\\nu)}$ (resolved,\nbetween-cell) and $\\sigma_{Y^\\perp}=\\|y^\\perp\\|_{L^2(\\nu)}$ (within-cell), where\n$y^\\star=\\mathsf{P}_K(y-\\mu)$, $y^\\perp=\\mathsf{P}_K^{\\perp}(y-\\mu)$ are the\ncell-averaging / within-cell projections of the OHC field $y\\in L^2(\\nu)$ and\n$\\nu$ is the normalized area$\\times$time reference measure on\n$\\mathcal{X}=A\\times\\mathcal{T}$. The one factor that cannot be estimated from a\nsparse point pattern, $\\sigma_{w^\\perp}$, enters only through the product\n$\\sigma_{w^\\perp}\\sigma_{Y^\\perp}$; it is therefore bias-irrelevant to the extent\nthe field is constant within cells. **So the cell scale must make the fraction\nof field variance below it, $\\sigma_{Y^\\perp}^2/\\sigma_Y^2$, small** — while\nkeeping the mean occupancy $N/K$ (in practice $F/K$, with $F$ the number of\ndistinct floats) above one.\n\nThe field factors, unlike $\\sigma_{w^\\star}$, are computable directly on the\ndense GLORYS field over the NAC box (lon $[-68,-62]$, lat $[36,40]$, 2020–2022\ndaily at $1/12^\\circ$), which resolves $\\sigma_{Y^\\star},\\sigma_{Y^\\perp},\\sigma_Y$\nexactly. This report fixes the resolution in two logically separate steps —\n**spatial** ($K_{\\mathrm{lon}},K_{\\mathrm{lat}}$) and **temporal** ($K_t$) —\nand, importantly, the spatial choice can be made *independently of seasonality*\n(see below), so we settle it first.\n\n::: {#setup .cell execution_count=2}\n``` {.python .cell-code code-summary=\"Setup — run (or load cached) R analyses\"}\nimport sys, os\nsys.path.insert(0, os.path.abspath(\"../code\"))\n\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\nimport resolution as R\n\nDEPTHS = [\"700\", \"2000\"]\nD = \"../data/leakage\"\nTIME_CSV, FULL_CSV, SPATIAL_CSV = f\"{D}/leakage_time.csv\", f\"{D}/leakage_full.csv\", f\"{D}/leakage_spatial.csv\"\nVG_RANGES, VG_CURVES, VG_ACF = f\"{D}/variogram_ranges.csv\", f\"{D}/variogram_curves.csv\", f\"{D}/variogram_acf.csv\"\nARGO_CSV, OCC_CSV, SWEEP_CSV = f\"{D}/argo_compare.csv\", f\"{D}/argo_occupancy.csv\", f\"{D}/argo_sweep.csv\"\n\nif not all(os.path.exists(p) for p in (TIME_CSV, FULL_CSV, SPATIAL_CSV)):\n    R.run_leakage_curves(TIME_CSV, FULL_CSV, SPATIAL_CSV, depths=DEPTHS)\nif not all(os.path.exists(p) for p in (VG_RANGES, VG_CURVES, VG_ACF)):\n    R.run_variogram(VG_RANGES, VG_CURVES, VG_ACF, depths=DEPTHS)\nif not all(os.path.exists(p) for p in (ARGO_CSV, OCC_CSV, SWEEP_CSV)):\n    R.run_argo_comparison(ARGO_CSV, OCC_CSV, SWEEP_CSV, depths=DEPTHS)\n\ntime_df, full_df, spatial_df = R.load_tables(TIME_CSV, FULL_CSV, SPATIAL_CSV)\nvg_ranges, vg_curves, vg_acf = R.load_tables(VG_RANGES, VG_CURVES, VG_ACF)\nargo_df, occ_df, sweep_df = R.load_tables(ARGO_CSV, OCC_CSV, SWEEP_CSV)\n```\n:::\n\n\n# Spatial resolution {#sec-spatial}\n\n::: {.callout-tip appearance=\"simple\"}\n**This section is free of seasonality.** The quantities below are *per-snapshot\nspatial* variances. A seasonal cycle that is (near) spatially uniform shifts\nevery location on a given day by the same amount, and an additive constant does\nnot change that day's spatial variance. So the spatial within-cell variance —\nand hence the choice of $K_{\\mathrm{lon}},K_{\\mathrm{lat}}$ — is settled on raw\nOHC without any deseasonalizing. Seasonality enters only the temporal scale,\nhandled separately in @sec-temporal.\n:::\n\nThe most direct test of a spatial grid is empirical: partition each daily\nsnapshot into $K_{\\mathrm{lon}}\\times K_{\\mathrm{lat}}$ equal-measure\n(lon $\\times \\sin$lat) cells, take the $\\cos(\\mathrm{lat})$ area-weighted\nwithin-cell spatial variance and total spatial variance, and average over\nsnapshots (`spatial_leakage` in `code/leakage_curve.R`, eq. *sigmaYperp-hat*\nevaluated on the native $1/12^\\circ$ grid). Their ratio is the **fraction of\nspatial field variance below the cell scale**, $\\sigma_{Y^\\perp}^2/\\sigma_Y^2$ —\nexactly the quantity the bound needs small. As cells shrink it must fall to\nzero; the question is how small it already is at the coarsest cell the floats\ncan support, $s_F\\approx 76$ km.\n\n::: {#cell-spatial-fraction .cell execution_count=3}\n\n::: {.cell-output .cell-output-stdout}\n```\n\n<div style=\"text-align:center\">\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](resolution_files/figure-html/spatial-fraction-output-2.png){#spatial-fraction width=662 height=431}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n</div>\n\n```\n:::\n:::\n\n\n::: {#spatial-table .cell execution_count=4}\n\n<table class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>depth</th>\n      <th>target_km</th>\n      <th>K_lon</th>\n      <th>K_lat</th>\n      <th>n_cells</th>\n      <th>cell (km)</th>\n      <th>var frac (perp^2/Y^2)</th>\n      <th>sd ratio (perp/Y)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>0-700 m</td>\n      <td>200</td>\n      <td>3</td>\n      <td>2</td>\n      <td>6</td>\n      <td>197.069</td>\n      <td>0.360</td>\n      <td>0.600</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>150</td>\n      <td>3</td>\n      <td>3</td>\n      <td>9</td>\n      <td>160.906</td>\n      <td>0.266</td>\n      <td>0.515</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>100</td>\n      <td>5</td>\n      <td>4</td>\n      <td>20</td>\n      <td>107.939</td>\n      <td>0.157</td>\n      <td>0.396</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>75</td>\n      <td>7</td>\n      <td>6</td>\n      <td>42</td>\n      <td>74.485</td>\n      <td>0.086</td>\n      <td>0.293</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>50</td>\n      <td>10</td>\n      <td>9</td>\n      <td>90</td>\n      <td>50.883</td>\n      <td>0.044</td>\n      <td>0.210</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>35</td>\n      <td>15</td>\n      <td>13</td>\n      <td>195</td>\n      <td>34.568</td>\n      <td>0.021</td>\n      <td>0.147</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>25</td>\n      <td>21</td>\n      <td>18</td>\n      <td>378</td>\n      <td>24.828</td>\n      <td>0.011</td>\n      <td>0.105</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>18</td>\n      <td>29</td>\n      <td>25</td>\n      <td>725</td>\n      <td>17.928</td>\n      <td>0.005</td>\n      <td>0.072</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>12</td>\n      <td>44</td>\n      <td>37</td>\n      <td>1628</td>\n      <td>11.964</td>\n      <td>0.002</td>\n      <td>0.043</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>200</td>\n      <td>3</td>\n      <td>2</td>\n      <td>6</td>\n      <td>197.069</td>\n      <td>0.324</td>\n      <td>0.570</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>150</td>\n      <td>3</td>\n      <td>3</td>\n      <td>9</td>\n      <td>160.906</td>\n      <td>0.238</td>\n      <td>0.487</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>100</td>\n      <td>5</td>\n      <td>4</td>\n      <td>20</td>\n      <td>107.939</td>\n      <td>0.135</td>\n      <td>0.367</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>75</td>\n      <td>7</td>\n      <td>6</td>\n      <td>42</td>\n      <td>74.485</td>\n      <td>0.072</td>\n      <td>0.268</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>50</td>\n      <td>10</td>\n      <td>9</td>\n      <td>90</td>\n      <td>50.883</td>\n      <td>0.036</td>\n      <td>0.189</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>35</td>\n      <td>15</td>\n      <td>13</td>\n      <td>195</td>\n      <td>34.568</td>\n      <td>0.017</td>\n      <td>0.131</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>25</td>\n      <td>21</td>\n      <td>18</td>\n      <td>378</td>\n      <td>24.828</td>\n      <td>0.009</td>\n      <td>0.093</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>18</td>\n      <td>29</td>\n      <td>25</td>\n      <td>725</td>\n      <td>17.928</td>\n      <td>0.004</td>\n      <td>0.064</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>12</td>\n      <td>44</td>\n      <td>37</td>\n      <td>1628</td>\n      <td>11.964</td>\n      <td>0.001</td>\n      <td>0.038</td>\n    </tr>\n  </tbody>\n</table>\n\n:::\n\n\nReading off the curve at $s_F\\approx76$ km fixes the spatial grid: the smallest\n$K_{\\mathrm{lon}}\\times K_{\\mathrm{lat}}$ whose cell size sits at or below the\ndecorrelation scale while keeping the residual fraction acceptably small. The\npaper's operating grid $K_{\\mathrm{lon}}=6,\\ K_{\\mathrm{lat}}=5$\n($\\Delta x\\approx88$ km, $\\Delta y\\approx89$ km) is read directly from this\ncurve.\n\n## Decorrelation length (directional variogram)\n\nThe variogram corroborates the cell-size curve above and, unlike it, exposes the\n**anisotropy** that the front imposes. Within each snapshot we form grid-point\npairs (subsampled), classify each by orientation, and accumulate the\nsemivariance $\\tfrac12(y_i-y_j)^2$ into zonal ($|\\theta|<30^\\circ$), meridional\n($|\\theta|>60^\\circ$) and omnidirectional bins, pooled over snapshots — again a\nper-snapshot construction, so again seasonality-free. It *must* be directional:\ncorrelation is long along the current and short across it, and an isotropic\naverage would hide the short across-front scale, which is the binding one. (Raw\nOHC has a per-snapshot planar trend removed so the standing Gulf-Stream gradient\ndoes not render the variogram non-stationary; the deseasonalized panel removes\nthe per-snapshot mean.)\n\n::: {#variograms .cell execution_count=5}\n\n::: {.panel-tabset}\n\n\n### 0-700 m\n\n\n<div style=\"text-align:center\">\n\n![](resolution_files/figure-html/variograms-output-2.png){#variograms-1 width=1143 height=418}\n\n</div>\n\n\n### 0-2000 m\n\n\n<div style=\"text-align:center\">\n\n![](resolution_files/figure-html/variograms-output-4.png){#variograms-2 width=1143 height=418}\n\n</div>\n\n\n:::\n\n:::\n\n\nThe binding relevance scale is the **shorter, meridional (across-front)** range:\n$\\sigma_{Y^\\perp}$ is controlled by field variation in *every* within-cell\ndirection, so the shortest one governs. The methodology's verdict is\n$L_{\\mathrm{rel}}\\gtrsim s_F=\\sqrt{|A|/F}\\approx76$ km (eq. *verdict*): the\nfield's shortest decorrelation length must be no finer than the scale the floats\ncan resolve. Where it holds, cells at the sampling scale sit within a\ndecorrelation length and $\\sigma_{Y^\\perp}$ is small; where it fails, a band of\nbias-relevant structure is unresolved and the residual term must be carried\nrather than assumed away.\n\n::: {#ranges-table .cell execution_count=6}\n\n<table class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>depth</th>\n      <th>field</th>\n      <th>direction</th>\n      <th>sill</th>\n      <th>range 1/e (km)</th>\n      <th>range exp (km)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>0-700 m</td>\n      <td>raw</td>\n      <td>omni</td>\n      <td>43.513</td>\n      <td>85.2</td>\n      <td>69.4</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>raw</td>\n      <td>zonal</td>\n      <td>43.513</td>\n      <td>100.0</td>\n      <td>118.1</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>raw</td>\n      <td>merid</td>\n      <td>43.513</td>\n      <td>76.1</td>\n      <td>50.3</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>deseas</td>\n      <td>omni</td>\n      <td>28.389</td>\n      <td>80.4</td>\n      <td>67.8</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>deseas</td>\n      <td>zonal</td>\n      <td>28.389</td>\n      <td>84.5</td>\n      <td>88.6</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>deseas</td>\n      <td>merid</td>\n      <td>28.389</td>\n      <td>76.3</td>\n      <td>51.8</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>raw</td>\n      <td>omni</td>\n      <td>90.477</td>\n      <td>89.0</td>\n      <td>72.7</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>raw</td>\n      <td>zonal</td>\n      <td>90.477</td>\n      <td>101.5</td>\n      <td>119.0</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>raw</td>\n      <td>merid</td>\n      <td>90.477</td>\n      <td>81.3</td>\n      <td>53.7</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>deseas</td>\n      <td>omni</td>\n      <td>59.914</td>\n      <td>87.6</td>\n      <td>76.7</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>deseas</td>\n      <td>zonal</td>\n      <td>59.914</td>\n      <td>88.9</td>\n      <td>97.2</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>deseas</td>\n      <td>merid</td>\n      <td>59.914</td>\n      <td>86.5</td>\n      <td>60.2</td>\n    </tr>\n  </tbody>\n</table>\n\n:::\n\n\n# Temporal resolution and seasonality {#sec-temporal}\n\n::: {.callout-note appearance=\"simple\"}\n**This section is where seasonality lives.** The number of time bins $K_t$ is\ngoverned by temporal structure of the regional-mean OHC series, which is\ndominated by the seasonal cycle; the spatial choice of @sec-spatial does not\ndepend on any of it.\n:::\n\nCollapsing space to the area-weighted regional mean $\\bar Y(t)$ (the\n$K_{\\mathrm{lon}}=K_{\\mathrm{lat}}=1$ special case of $\\mathcal{P}_K$), we bin\nthe 2020–2022 series into $K_t$ equal-duration bins and report the fraction of\nits temporal variance left within bins, $\\sigma_{Y^\\perp}^2/\\sigma_Y^2$, for the\n**raw** series and for a **deseasonalized** series (minus a per-cell,\nper-calendar-month GLORYS climatology — an Argo-independent baseline). The gap\nbetween them is the seasonal cycle: the raw fraction stays large until many time\nbins resolve the seasonal swing, whereas deseasonalizing removes it up front so\neven a coarse $K_t$ leaks little.\n\n::: {#temporal-fraction .cell execution_count=7}\n\n::: {.panel-tabset}\n\n\n## 0-700 m\n\n\n<div style=\"text-align:center\">\n\n![](resolution_files/figure-html/temporal-fraction-output-2.png){#temporal-fraction-1 width=664 height=431}\n\n</div>\n\n\n## 0-2000 m\n\n\n<div style=\"text-align:center\">\n\n![](resolution_files/figure-html/temporal-fraction-output-4.png){#temporal-fraction-2 width=664 height=431}\n\n</div>\n\n\n:::\n\n:::\n\n\nThe lagged autocorrelation of the deseasonalized regional mean gives the\nresidual (non-seasonal) temporal decorrelation scale; its $e$-folding lag,\ntogether with the seasonal amplitude above, sets $K_t$.\n\n::: {#cell-temporal-acf .cell execution_count=8}\n\n::: {.cell-output .cell-output-stdout}\n```\n\n<div style=\"text-align:center\">\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](resolution_files/figure-html/temporal-acf-output-2.png){#temporal-acf width=645 height=412}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n</div>\n\n```\n:::\n:::\n\n\n::: {#temporal-table .cell execution_count=9}\n\n<table class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>depth</th>\n      <th>K_t</th>\n      <th>raw</th>\n      <th>deseas</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>0-700 m</td>\n      <td>3</td>\n      <td>0.968</td>\n      <td>0.941</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>6</td>\n      <td>0.528</td>\n      <td>0.728</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>12</td>\n      <td>0.483</td>\n      <td>0.657</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>24</td>\n      <td>0.225</td>\n      <td>0.327</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>3</td>\n      <td>0.936</td>\n      <td>0.905</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>6</td>\n      <td>0.608</td>\n      <td>0.733</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>12</td>\n      <td>0.564</td>\n      <td>0.668</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>24</td>\n      <td>0.294</td>\n      <td>0.363</td>\n    </tr>\n  </tbody>\n</table>\n\n:::\n\n\n# Operating partition {#sec-operating}\n\nOn the full partition $\\mathcal{P}_K$ at the operating spatial grid\n($K_{\\mathrm{lon}}=6,\\ K_{\\mathrm{lat}}=5$), the combined field variance splits\nby the Pythagorean identity $\\sigma_Y^2=\\sigma_{Y^\\star}^2+\\sigma_{Y^\\perp}^2$\n(eq. *sigmaYK-hat / sigmaYperp-hat*, native grid aggregated to equal-measure\ncells). The residual diagnostic there, across $K_t$:\n\n::: {#operating-checks .cell execution_count=10}\n\nPythagorean identity holds by construction (max residual $2.8e-14$); the equal-measure quadrature reconstructs the direct $\\cos(\\mathrm{lat})$-weighted field variance to within **0.8%** (largest relative gap across resolutions), bounding the error of treating the discrete cells as exactly equal-measure.\n\n\nCombined space$\\times$time variance fraction $\\sigma_{Y^\\perp}^2/\\sigma_Y^2$:\n\n\n<table class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>depth</th>\n      <th>K_t</th>\n      <th>raw</th>\n      <th>deseas</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>0-700 m</td>\n      <td>3</td>\n      <td>0.332</td>\n      <td>0.965</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>6</td>\n      <td>0.308</td>\n      <td>0.918</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>12</td>\n      <td>0.276</td>\n      <td>0.826</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>24</td>\n      <td>0.224</td>\n      <td>0.682</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>3</td>\n      <td>0.303</td>\n      <td>0.957</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>6</td>\n      <td>0.285</td>\n      <td>0.913</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>12</td>\n      <td>0.251</td>\n      <td>0.805</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>24</td>\n      <td>0.199</td>\n      <td>0.648</td>\n    </tr>\n  </tbody>\n</table>\n\n:::\n\n\n# Observed Argo profiles vs GLORYS truth {#sec-argo}\n\nEverything above is computed on the dense GLORYS field, i.e. against the\nreference measure $\\nu$. The real Argo profiles instead realize the *sampling*\nmeasure $\\pi$: their spatial–temporal locations are a point pattern with\nintensity proportional to $\\pi$, and their OHC is the field sampled at those\npoints. Using the observed profile OHC (`data/argo_ohc.csv`, restricted to the\nsame NAC box and 2020–2022) we can (i) measure how uneven the sampling actually\nis — the between-cell weight dispersion $\\sigma_{w^\\star}$ that the GLORYS field\nalone cannot supply — and (ii) check whether the sparse, clustered sample\n*recovers* the field's within/between-cell OHC structure or distorts it, as\npreferential sampling would. This is the empirical counterpart of the bias\nbound: it pairs the observed $\\sigma_{w^\\star}$ with the GLORYS $\\sigma_{Y^\\star}$.\n\n::: {.callout-warning appearance=\"simple\"}\n**Depth reliability.** In this box $99\\%$ of profiles reach $700$ m but only\n$\\sim\\!5\\%$ reach $2000$ m (median profile depth $\\approx 1980$ m). The Argo\n$0$–$2000$ m OHC is therefore integrated over a truncated, profile-dependent\ncolumn: this biases its *mean* low and inflates its *within-cell variance*\nindependently of sampling. **The $0$–$700$ m comparison is the clean one and we\nread the conclusions from it;** $0$–$2000$ m is shown for completeness under\nthis caveat.\n:::\n\n## Sampling weights (occupancy)\n\nOn the operating grid, occupancy estimates the cell sampling probability\n$\\pi_j = n_j/N$ and hence the between-cell weight $\\bar w_j = K\\pi_j$\n($\\bar w_j = 1$ is uniform, $\\nu$-matched sampling). Its dispersion is the\nresolved sampling factor\n$\\sigma_{w^\\star}^2 = \\tfrac1K\\sum_j(\\bar w_j-1)^2$ (eq. *sigma-w-parts*).\n\n::: {#argo-occupancy .cell execution_count=11}\n\n\n### 0-700 m\n\n\n\n<div style=\"text-align:center\">\n\n![](resolution_files/figure-html/argo-occupancy-output-2.png){#argo-occupancy-1 width=675 height=412}\n\n</div>\n\n\n\n### 0-2000 m\n\n\n\n<div style=\"text-align:center\">\n\n![](resolution_files/figure-html/argo-occupancy-output-4.png){#argo-occupancy-2 width=675 height=412}\n\n</div>\n\n:::\n\n\nThe profiles keep all $K_{\\mathrm{lon}}\\times K_{\\mathrm{lat}}=30$ operating\ncells populated ($\\geq 5$ profiles each), with a moderate resolved dispersion\n$\\sigma_{w^\\star}\\approx 0.34$. Occupancy is the binding constraint on how fine\nthe grid can go: as cells shrink past the float floor $s_F$, cells empty out and\nthe within-cell terms become inestimable.\n\n\n<div style=\"text-align:center\">\n\n![](resolution_files/figure-html/argo-sweep-output-2.png){#argo-sweep width=660 height=431}\n\n</div>\n\n\n\n## Within- and between-cell OHC: Argo vs GLORYS\n\nFor each $K_t$ the profiles are binned into the same equal-measure\n$\\mathcal{P}_K$ cells; cell means and within-cell variances are taken over the\nprofiles (unweighted — the sample already carries the sampling intensity), and\nthe field factors use equal cell weight $1/K$. Solid lines are the GLORYS truth\n(reference measure); open markers the Argo sample.\n\n::: {#argo-compare .cell execution_count=13}\n\n\n### 0-700 m\n\n\n\n<div style=\"text-align:center\">\n\n![](resolution_files/figure-html/argo-compare-output-2.png){#argo-compare-1 width=1047 height=419}\n\n</div>\n\n\n\n### 0-2000 m\n\n\n\n<div style=\"text-align:center\">\n\n![](resolution_files/figure-html/argo-compare-output-4.png){#argo-compare-2 width=1047 height=419}\n\n</div>\n\n:::\n\n\nAt $0$–$700$ m the sparse sample recovers the field structure well: the\nbetween-cell factor $\\sigma_{Y^\\star}$ and the within-cell fraction\n$\\sigma_{Y^\\perp}^2/\\sigma_Y^2$ track the GLORYS truth closely, with the Argo\n$\\sigma_{Y^\\perp}$ mildly inflated (few profiles per cell, and profiles in a\ncell span different days within the time bin add temporal spread to the \"spatial\"\nwithin-cell term). At $0$–$2000$ m the Argo within-cell fraction is visibly\ninflated relative to truth — the variable profile-depth truncation flagged above,\nnot a property of the field.\n\n## Realized bias and the design-based cap\n\nThe naive profile average $\\hat\\mu_\\pi = \\tfrac1N\\sum_i y_i$ is the $\\pi$-mean;\nits gap from the GLORYS $\\nu$-mean $\\mu$ is the *realized* discrepancy, while\nthe cell-averaged estimator $\\hat\\mu_{\\mathrm{grid}} = \\tfrac1K\\sum_j\\bar y_j$\npartially corrects the between-cell oversampling. The design-based **between-cell\ncap** $\\sigma_{w^\\star}\\sigma_{Y^\\star}$ (observed $\\sigma_{w^\\star}$, truth\n$\\sigma_{Y^\\star}$) bounds the *preferential-sampling* part of the bias.\n\n::: {#argo-bias .cell execution_count=14}\n\n<table class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>depth</th>\n      <th>K_t</th>\n      <th>sigma_w*</th>\n      <th>sigma_Y* (GJ)</th>\n      <th>cap sigma_w*sigma_Y* (GJ)</th>\n      <th>|bias| naive (GJ)</th>\n      <th>|bias| grid (GJ)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>0-700 m</td>\n      <td>1</td>\n      <td>0.343</td>\n      <td>8.80</td>\n      <td>3.02</td>\n      <td>2.74</td>\n      <td>2.30</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>3</td>\n      <td>0.598</td>\n      <td>8.86</td>\n      <td>5.29</td>\n      <td>2.74</td>\n      <td>1.88</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>6</td>\n      <td>0.852</td>\n      <td>9.02</td>\n      <td>7.68</td>\n      <td>2.74</td>\n      <td>2.50</td>\n    </tr>\n    <tr>\n      <td>0-700 m</td>\n      <td>12</td>\n      <td>1.136</td>\n      <td>9.22</td>\n      <td>10.48</td>\n      <td>2.74</td>\n      <td>2.40</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>1</td>\n      <td>0.342</td>\n      <td>13.65</td>\n      <td>4.67</td>\n      <td>7.39</td>\n      <td>6.80</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>3</td>\n      <td>0.593</td>\n      <td>13.74</td>\n      <td>8.15</td>\n      <td>7.39</td>\n      <td>5.99</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>6</td>\n      <td>0.847</td>\n      <td>13.92</td>\n      <td>11.79</td>\n      <td>7.39</td>\n      <td>6.92</td>\n    </tr>\n    <tr>\n      <td>0-2000 m</td>\n      <td>12</td>\n      <td>1.132</td>\n      <td>14.24</td>\n      <td>16.13</td>\n      <td>7.39</td>\n      <td>6.81</td>\n    </tr>\n  </tbody>\n</table>\n\n\nAt $0$–$700$ m the naive profile mean underestimates the GLORYS truth by **2.74 GJ m$^{-2}$** ($-6.0\\%$ of $\\mu=46.0$), and cell-averaging trims this to 2.30. Even the tightest, pure-spatial cap ($K_t=1$) $\\sigma_{w^\\star}\\sigma_{Y^\\star}=3.02$ GJ m$^{-2}$ contains it — whereas at $0$–$2000$ m the truncation-inflated gap exceeds that cap, confirming it is not sampling alone.\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n**What this gap does and does not isolate.** The realized naive/grid discrepancy\nconflates preferential sampling with any systematic GLORYS-vs-observation offset\n(reanalysis mean-state bias, representativeness) — and at $0$–$2000$ m with the\ndepth truncation above, which is why the $2000$ m $|$bias$|$ can exceed the\npreferential-sampling cap. Only the design-based product\n$\\sigma_{w^\\star}\\sigma_{Y^\\star}$ (plus the within-cell term) isolates the\nsampling contribution as a worst case. The clean sampling-only bias — GLORYS\nco-located at the float positions, same field on both sides — is the subject of\nthe main sampling-bias experiment; this section is an independent check with the\nreal profiles that the sampling is preferential ($\\sigma_{w^\\star}>0$) and that\nthe field structure the bound relies on is recoverable from the observed sample.\n:::\n\n",
    "supporting": [
      "resolution_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}