project:
  type: website
  render:
    - "index.qmd"
    # - "reports/pilot_simulation.qmd"  # temporarily disabled to speed up nac.qmd preview
    - "reports/nac.qmd"
    - "reports/nac_gp.qmd"

execute:
  freeze: auto

website:
  title: "Argo Bias"
  page-navigation: true
  search: false

  repo-url: https://github.com/dannymross/argo_bias

  sidebar:
    style: docked
    contents:
      - index.qmd
      - section: reports/nac.qmd
        contents:
          - text: "Goal and design"
            href: reports/nac.qmd#goal-and-design
          - text: "Setup"
            href: reports/nac.qmd#setup
          - text: "Analysis region"
            href: reports/nac.qmd#analysis-region
          - text: "OHC Anomaly"
            href: reports/nac.qmd#ohc-anomaly
      - section: reports/nac_gp.qmd
        contents:
          - text: "Setup"
            href: reports/nac_gp.qmd#setup
          - text: "GP Modeling"
            href: reports/nac_gp.qmd#gp-modeling

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: false
    number-sections: false
    code-tools: false
    fig-align: center
