project:
  type: website
  render:
    - "index.qmd"
    - "reports/bias_bound_motivation.qmd"
    - "reports/bias_bound_sampling.qmd"
    - "reports/bias_bound_permutation.qmd"
    #- "reports/bias_bound_prediction.qmd"
    #- "reports/bias_bound_validation.qmd"
    #- "reports/bias_bound_outlook.qmd"
    #- "reports/pilot_simulation.qmd"  # temporarily disabled to speed up nac.qmd preview
    - "reports/nac.qmd"
    - "reports/nac_gp.qmd"

execute:
  freeze: auto

website:
  title: "Argo Bias"
  page-navigation: true
  search: false

  repo-url: https://github.com/dannymross/argo_bias

  sidebar:
    style: docked
    contents:
      - index.qmd
      - section: "Methodology"
        contents:
          - reports/bias_bound_motivation.qmd
          - reports/bias_bound_sampling.qmd
          - reports/bias_bound_permutation.qmd
          #- reports/bias_bound_prediction.qmd
          #- reports/bias_bound_validation.qmd
          #- reports/bias_bound_outlook.qmd
      - section: "North Atlantic Current"
        contents:
          - reports/nac.qmd
          - reports/nac_gp.qmd
          

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    number-sections: false
    code-tools: false
    fig-align: center
