project:
  type: website
  render:
    - "index.qmd"
    # - "reports/pilot_simulation.qmd"  # temporarily disabled to speed up nac.qmd preview
    - "reports/nac.qmd"
    - "reports/nac_gp.qmd"

execute:
  freeze: auto

website:
  title: "Argo Bias"
  page-navigation: true

  repo-url: https://github.com/dannymross/argo_bias

  navbar:
    title: "Argo Bias"
    search: false
    left:
      - icon: journal-text
        menu:
          - href: reports/pilot_simulation.qmd
            text: "Pilot Simulation"
          - href: reports/nac.qmd
            text: "NAC Targeted Analysis"
          - href: reports/nac_gp.qmd
            text: "NAC GP Modeling"
    right:
      - icon: github
        href: https://github.com/dannymross/argo_bias

  sidebar: false


format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: false
    number-sections: false
    code-tools: false
    fig-align: center
