name: argo_bias
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipython
  - jupyter
  - ipykernel
  - jupyter-cache
  - numpy
  - pandas
  - xarray
  - matplotlib
  - cartopy
  - pip
  - parcels
  - copernicusmarine
  - pip:
    - global_land_mask
    - git+https://github.com/euroargodev/VirtualFleet.git
