---
title: "argo bias"
subtitle: "project planning"
format:
  html:
    theme: default
    toc: true
    toc-title: "contents"
    toc-depth: 4
    toc-location: right
    number-sections: true
lightbox: true
execute:
  echo: true
  warning: false
  message: false
  prompt: true
  fig-align: center
  fig-width: 7.5
  fig-height: 6
knitr:
  opts_chunk:
    prompt: false
    collapse: false
editor_options:
  chunk_output_type: console
---

# eda

```{r}
options(digits = 4, scipen = 999)

root <- getwd()
library(tidyverse)
library(data.table)
library(pbapply)
library(geosphere)
library(GpGp)

load(paste0(root, "/data/argo_velo_data_january.RData"))
```

## velocity

### number of floats in data
```{r}
argo[,.(
  n_floats = uniqueN(float_id),
  dates_floats = paste0(range(isodatetime), collapse = "-")
), float_r]

A <- argo[(float_r)]

float_n <- A[,.N,float_id]
summary(float_n$N)
hist(float_n$N, breaks = seq(0,44,1), main = "obs per float", xlab = "n")
```

### surfacing/observation frequency
```{r}
A[, dt_day := dt_s / (60^2 * 24)]
summary(A$dt_day)
B <- A[!is.na(dt_day), .N, dt_day]

par(mfrow = c(2,2))
hist(A$dt_day, breaks = seq(0,2500,1), main = "obs freq", xlab = NULL)
hist(A[dt_day < 50, dt_day], breaks = seq(0,50,.5), main = "0-50 days", xlab = NULL)
hist(A[between(dt_day,300,400), dt_day], breaks = seq(300,400,1), main = "300-400 days", xlab = NULL)
hist(A[between(dt_day,680,780), dt_day], breaks = seq(680,780,1), main = "680-780 days", xlab = NULL)

b <- c(0,9,11,300,400,1000,2500)
B[, cat := cut(dt_day, breaks = b, dig.lab = 5)]
B[,.(obs = sum(N)),keyby = cat][,prop := obs / sum(obs)][, c_prop := cumsum(prop)][]
```

### add ocean region data

`mregions2` downloads shapefiles from <https://www.marineregions.org/sources.php#goas>
```{r}
library(sf)
sf_use_s2(FALSE)
library(mregions2)

goas_file <- paste0(root,"/data/goas.rds")

if (file.exists(goas_file)) {
  goas <- readRDS(goas_file)
} else {
  goas <- mrp_get("goas")
  saveRDS(goas, goas_file)
}

float_loc <- A[,.(float_id, float_i, lon_degrees, lat_degrees)]
float_loc_sf <- st_as_sf(float_loc, coords = c("lon_degrees", "lat_degrees"), crs = 4326) # WGS84 globe

float_loc_j <- st_join(float_loc_sf, goas["name"])
float_loc_j <- as.data.table(float_loc_j)[, geometry := NULL]
setnames(float_loc_j, c("name"), c("ocean")) 
float_loc_j[, ocean := tolower(ocean)] 

setkey(float_loc_j, float_id, float_i)
setkey(float_loc, float_id, float_i)

float_loc <- float_loc[float_loc_j]

float_loc[,.(
  .N,
  lat_range = paste0(round(range(lat_degrees),2), collapse = ","),
  lon_range = paste0(round(range(lon_degrees),2), collapse = ",")),
.(ocean)][order(-N)]

sample_locs <- float_loc[, .SD[sample(.N, min(1000, .N))], by = ocean]

map_pts <- function(df, x = "lon_degrees", y = "lat_degrees", color = "ocean", legend.rows = 1){
  ggplot() +
  borders("world", fill = "gray80", colour = "gray80") +
  geom_point(data = df,
    aes(x = .data[[x]],
        y = .data[[y]],
        color = .data[[color]]), size = .5) +
  coord_sf() +
  theme_minimal() +
  theme(legend.position = "bottom") +
  guides(colour = guide_legend(ncol = legend.rows))
}

map_pts(sample_locs, color = "ocean", legend.rows = 3)
```

```{r}
setkey(A, float_id, float_i, lon_degrees, lat_degrees)
setkey(float_loc, float_id, float_i, lon_degrees, lat_degrees)

A <- A[float_loc]
```

### explore speed/velocity within north atlantic ocean
```{r}
NAO <- A[ocean %in% c("north atlantic ocean")]
NAO[, has10 := any(between(dt_day,9,11)), float_id]
NAO <- NAO[(has10),]
map_pts(NAO, color = "speed_ms") + 
  coord_sf(xlim = c(-80,5), ylim = c(0,65)) +
  scale_color_viridis_c(option = "plasma", na.value = "grey80") +
  guides(color = guide_colorbar())

fid <- NAO[which.max(float_i), float_id]
X <- NAO[float_id == fid]
map_pts(X, color = "speed_ms") +
  coord_sf(xlim = c(-80,5), ylim = c(0,65)) +
  scale_color_viridis_c(option = "plasma", na.value = "grey80") +
  guides(color = guide_colorbar())
```

#### correlation between speed/velocity at ohc
```{r}
X <- NAO[!is.na(speed_ms),.(speed_ms, u_ms, v_ms, z)]
cor(X)
cor.test(X$speed_ms, X$z)
cor.test(X$u_ms, X$z)
cor.test(X$v_ms, X$z)
```

```{r}
#S <- NAO[1:2, .(float_id, max_depth, obs_pressures, obs_temps, )]
```

<!--
- calc. radius of drift (by region)
- do floats replace eachother in the same area? eg does a float move out of an initial radius but a different float moves into that initial radius?
  - within a fixed region (basins) how much area is covered by the floats over time? do they begin to cluster or do they circle and replace eachother such that the same area is covered?
- discuss distance metrics to calc. velocity
-->
