---
title: "argo bias"
subtitle: "exploratory analysis notebook"
author : daniel ross
date-modified: last-modified
date-format: "YYYY-MM-DD HH:mm"
format:
  html:
    theme: default
    toc: true
    toc-depth: 6
    toc-title: "contents"
    toc-location: right
    number-sections: true
    code-fold: true
    code-tools: true
    embed-resources: false
lightbox: true
execute:
  cache: true
  warning: false
  message: false
  prompt: true
  fig-align: center
  fig-width: 11
  fig-height: 8.5
params:
  archive_eval: false
knitr:
  opts_chunk:
    prompt: false
    collapse: false
editor_options:
  chunk_output_type: console
---

```{r}
#| label: helpers
#| cold-fold: show
source("../code/velocity_helpers.R")
source("../code/plot_helpers.R")
```

```{r}
#| label: argo_ohc_processing
#| colde-fold: show
argo_ohc <- fread("../data/argo_ohc.csv") %>% 
  add_velocity_enu() %>% 
  add_dtemp()
```

# north atlantic current
- targeted analysis of north atlantic current
- filter to floats that ever enter the current and are observed regularly, ~every 10 days

```{r}
#| label: nac_processing

setkey(argo_ohc, float_id, date)
argo_ohc[, float_obs_n := 1:.N, float_id]
argo_ohc[, float_r := any(float_obs_n > 1), float_id]

argo_ohc[, year := year(date)]
argo_ohc[, month := month(date)]

nac_lat <- c(25,80)
nac_lon <- c(-80, 30)
argo_ohc[, nac := FALSE]
argo_ohc[between(lat,nac_lat[1],nac_lat[2]) & between(lon,nac_lon[1],nac_lon[2]), nac := TRUE]
argo_ohc[lon >= -6 & lat <= 46, nac := FALSE]

argo_ohc[, float_nac := any(nac), float_id]
argo_ohc[, float_nac_other := float_nac & any(!nac), float_id]

argo_ohc[, dt_day := dt_s / (60^2 * 24)]
argo_ohc[, dt_day_10 := FALSE]
argo_ohc[between(dt_day, 9.5, 10.5), dt_day_10 := TRUE]
argo_ohc[float_obs_n == 1, dt_day_10 := NA]
argo_ohc[, float_has_dt_day_10 := any(dt_day_10, na.rm = T), float_id]
argo_ohc[, float_all_dt_day_10 := all(dt_day_10, na.rm = T), float_id]

argo_nac <- argo_ohc[(float_nac) & (float_r)]
argo_nac_other <- argo_ohc[(float_nac_other)]
```

## 10 day floats 
```{r}
#| label: 10_day_floats
argo_nac[,.(floats = uniqueN(float_id), obs = .N), .(float_has_dt_day_10, float_all_dt_day_10)]

argo_nac_clean <- argo_nac[(float_all_dt_day_10)]
any_nac_lat <- argo_nac_clean[, range(lat)] 
any_nac_lon <- argo_nac_clean[, range(lon)]
```

## outlier ohc change
```{r}
#| label: dohc_outliers
argo_nac_clean[, abs_dohc_700 := abs(dohc_700)]
argo_nac_clean[, abs_dohc_2000 := abs(dohc_2000)]
q700 <- quantile(argo_nac_clean$abs_dohc_700, probs = seq(0, 1, 0.005), na.rm = TRUE)
q2000 <- quantile(argo_nac_clean$abs_dohc_2000, probs = seq(0, 1, 0.005), na.rm = TRUE)
argo_nac_clean[, dohc_o := F]
argo_nac_clean[(abs_dohc_700 > q700["99.0%"]) | (abs_dohc_2000 > q2000["99.0%"]), dohc_o := T]
argo_nac_clean[, float_has_dohc_o := any(dohc_o), float_id]
```

```{r}
#| label: dohc_outlier_plots
plot(x=q700,y=q2000)
abline(v=q700["99.0%"], h=q2000["99.0%"], col="red")
```

```{r}
#| label: nac_float_summary
argo_nac_clean[,.(
  floats = uniqueN(float_id),
  floats_outlier_ohc = uniqueN(float_id[(float_has_dohc_o)]),
  obs = .N
)]
argo_nac_clean[,.(
  floats = uniqueN(float_id),
  floats_new = sum(float_obs_n == 1),
  floats_outlier_dohc = uniqueN(float_id[(dohc_o)]),
  obs = .N,
  obs_dohc_o = sum(dohc_o)
), keyby = c("year")
]

obs_p_float <- argo_nac_clean[,.(
  obs = .N
),float_id]
summary(obs_p_float$obs)
hist(obs_p_float$obs, breaks = seq(0,510,10))
```

### float trajectory

#### cohort
```{r}
#| label: float_cohort

float_cohort <- argo_nac_clean[year==2011 & float_obs_n==1, unique(float_id)]
argo_nac_clean[float_id %in% float_cohort,.(
  floats = uniqueN(float_id),
  floats_new = sum(float_obs_n == 1),
  obs = .N
), keyby = c("year")
]
```

```{r}
#| label: float_cohort_anim
#| eval: false
map_trace_anim(
  argo_nac_clean[float_id %in% float_cohort],
  fps = 4,
  wake_length = .05,
  xlim = any_nac_lon,
  ylim = any_nac_lat,
  title = "north atlantic current - 10 day obs floats - 2011 cohort",
  z = "dohc_700",
  voption = "plasma",
  filename = "anim/argo_nac_cohort_anim.mp4"
)
```
{{< video anim/argo_nac_cohort_anim.mp4 >}}

#### all
```{r}
#| label: float_anim
#| eval: false
map_trace_anim(
  argo_nac_clean,
  fps = 4,
  wake_length = .05,
  xlim = any_nac_lon,
  ylim = any_nac_lat,
  title = "north atlantic current - 10 day obs floats",
  z = "dohc_700",
  voption = "plasma",
  filename = "anim/argo_nac_float_anim.mp4"
)
```

{{< video anim/argo_nac_float_anim.mp4 >}}

#### dohc outliers
```{r}
#| label: float_outlier_anim
#| eval: false
map_trace_anim(
  argo_nac_clean[(float_has_dohc_o)],
  fps = 4,
  wake_length = .05,
  xlim = any_nac_lon,
  ylim = any_nac_lat,
  title = "north atlantic current - 10 day obs floats with dohc outlier",
  z = "dohc_700",
  voption = "plasma",
  filename = "anim/argo_nac_float_dohco_anim.mp4"
)
```

{{< video anim/argo_nac_float_dohco_anim.mp4 >}}

## grid plots

### all
```{r}
#| label: map_grid
map_grid(
  argo_nac_clean,
  map_sum_pts,
  z = c("dohc_700","dohc_2000","u_ms","v_ms"),
  voptions = c("plasma","plasma","viridis","viridis"),
  xlim = any_nac_lon,
  ylim = any_nac_lat,
  binwidth = c(.5,.5),
  title = TeX(r"(velocity and $\Delta$ohc)"),
  subtitle = "north atlantic current"
)
```

### dohc outliers
```{r}
#| label: map_grid_outliers
map_grid(
  argo_nac_clean[(dohc_o)],
  map_sum_pts,
  z = c("dohc_700","dohc_2000","u_ms","v_ms"),
  voptions = c("plasma","plasma","viridis","viridis"),
  xlim = any_nac_lon,
  ylim = any_nac_lat,
  binwidth = c(.5,.5),
  title = TeX(r"(velocity and $\Delta$ohc)"),
  subtitle = "north atlantic current"
)
```

## trace plots
### all
```{r}
#| label: map_grid_trace
map_grid(
  argo_nac_clean,
  map_trace,
  z = c("dohc_700","dohc_2000","u_ms","v_ms","float_obs_n"),
  voptions = c("plasma","plasma","viridis","viridis","magma"),
  xlim = any_nac_lon,
  ylim = any_nac_lat,
  title = TeX(r"(velocity and $\Delta$ohc)"),
  subtitle = "north atlantic current"
)
```

### has dohc outlier obs
```{r}
#| label: map_grid_trace_outlier
map_grid(
  argo_nac_clean[(float_has_dohc_o)],
  map_trace,
  z = c("dohc_700","dohc_2000","u_ms","v_ms","float_obs_n"),
  voptions = c("plasma","plasma","viridis","viridis","magma"),
  xlim = any_nac_lon,
  ylim = any_nac_lat,
  title = TeX(r"(velocity and $\Delta$ohc)"),
  subtitle = "north atlantic current"
)
```

### correlation
```{r}
#| label: correlation
X <- argo_nac_clean[!is.na(u_ms),.(u_ms,v_ms,dohc_700,dohc_2000)]
cor(X, use = "complete.obs")
X <- argo_nac_clean[(float_has_dohc_o) & !is.na(u_ms),.(u_ms,v_ms,dohc_700,dohc_2000)]
cor(X, use = "complete.obs")
X <- argo_nac_clean[!(float_has_dohc_o) & !is.na(u_ms),.(u_ms,v_ms,dohc_700,dohc_2000)]
cor(X, use = "complete.obs")
```

```{r}
#| label: velo_dohc_plots
p1 <- plot_velocity_heatmap(argo_nac_clean[!is.na(u_ms)], z = "dohc_700")
p2 <- plot_velocity_heatmap(argo_nac_clean[!is.na(u_ms)], z = "dohc_2000")
p1 + p2

p1 <- plot_velocity_heatmap(argo_nac_clean[(float_has_dohc_o) & !is.na(u_ms)], z = "dohc_700")
p2 <- plot_velocity_heatmap(argo_nac_clean[(float_has_dohc_o) & !is.na(u_ms)], z = "dohc_2000")
p1 + p2

p1 <- plot_velocity_heatmap(argo_nac_clean[!(float_has_dohc_o) & !is.na(u_ms)], z = "dohc_700")
p2 <- plot_velocity_heatmap(argo_nac_clean[!(float_has_dohc_o) & !is.na(u_ms)], z = "dohc_2000")
p1 + p2
```

# reananalysis
```{r}
#| label: en4_read
ohc_en4 <- readRDS("../data/ohc_en4_gridded.rds")
setDT(ohc_en4)
ohc_cols <- grep("ohc", names(ohc_en4), value=T)
ohc_en4[, (ohc_cols) := lapply(.SD, \(x) x / 1e9), .SDcols = ohc_cols]
```

## north atlantic current
```{r}
#| label: en4_nac
nac_lat <- c(18,80)
nac_lon <- c(-80, 30)
ohc_en4[, nac := FALSE]
ohc_en4[between(lat,nac_lat[1],nac_lat[2]) & between(lon,nac_lon[1],nac_lon[2]), nac := TRUE]
#ohc_en4[lon >= -6 & lat <= 46, nac := FALSE]

ohc_en4_nac <- ohc_en4[(nac)]
```

```{r}
#| label: en4_ohc_anim
#| eval: false
map_sum_pts_anim(ohc_en4_nac, z = "ohc_700", time = "date",xlim = any_nac_lon, ylim = any_nac_lat, binwidth = c(1, 1), fps = 4, 
  filename = "anim/ohc_en4_nac.mp4")
```

{{< video anim/ohc_en4_nac.mp4 >}}
